/*****************************************************************
	7UP
	Heade: GRAF_.H
	
	Ersatzfunktion. Macht die Maus nicht um jeden Preis sichtbar.
*****************************************************************/

#ifndef GRAF__H
#define GRAF__H

/*****************************************************************
	Prototypen
*****************************************************************/
int graf_mouse_on(int on);

#endif /* GRAF__H */